direction: right
sourcefile: ソースファイル\n(テキストファイル) {
	shape: cylinder
}

destnationfile: "" {
	shape: cylinder
	imagetype: |md
		　  
		画像ファイル
		* svg
		* png
		* jpg
		* pdf
		* etc\.\.\.  
		(ツールやツールの設定による)
	|
}
softwares: "" {
	shape: rectangle
	softs: |md
		　変換
		===
		* PlantUML
		* Graphviz
		* Marmaid.js
		* D2
		* etc\.\.\.
	|
}
sourcefile -> softwares -> destnationfile
