@startwbs
* Instant Karma
** Current Member
*** Takapii
**** Vocal
*** Syun
**** Guitar
*** Michee
**** Vocal
**** Keyboard
*** Tetsu
**** Vocal
**** Bass
*** Toku
**** Drums

** Past Member
*** Ken
**** Vocal
**** Guitar
**** Bass
**** Drums
*** OrzBruford
**** Drums
@endwbs
