@startwbs
* Instant Karma
** Member
*** Current
**** Takapii
***** Vocal
**** Syun
***** Guitar
**** Michee
***** Vocal
***** Keyboard
**** Tetsu
***** Vocal
***** Bass
**** Toku
***** Drums

*** Past
**** Ken
***** Vocal
***** Guitar
***** Bass
***** Drums
**** OrzBruford
***** Drums
@endwbs
